LOCAL_PATH:=$(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS:=optional

LOCAL_SHARED_LIBRARIES:= liblog libutils
LOCAL_SRC_FILES:=hello.c

LOCAL_MODULE_PATH:=$(TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_MODULE:=hello.default
include $(BUILD_SHARED_LIBRARY)
