OBJ=find_max_sub_secquence find_close_zero_sequence
.PHONY:all clean
all:$(OBJ)
CFLAGS="-lm"
find_max_sub_secquence:find_max_sub_secquence.c
find_close_zero_sequence:find_close_zero_sequence.c

clean:
	rm -rf $(OBJ) *.o
